/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeQrPassRouteImport } from './routes/employee/qr-pass'
import { Route as EmployeePaymentsRouteImport } from './routes/employee/payments'
import { Route as EmployeeNewBookingRouteImport } from './routes/employee/new-booking'
import { Route as EmployeeMyBookingsRouteImport } from './routes/employee/my-bookings'
import { Route as EmployeeGuestHousesRouteImport } from './routes/employee/guest-houses'
import { Route as EmployeeFeedbackRouteImport } from './routes/employee/feedback'
import { Route as EmployeeDashboardRouteImport } from './routes/employee/dashboard'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as EmployeeQrPassBookingIdRouteImport } from './routes/employee/qr-pass.$bookingId'
import { Route as EmployeePaymentBookingIdRouteImport } from './routes/employee/payment.$bookingId'
import { Route as EmployeeGuestHousesIdRouteImport } from './routes/employee/guest-houses.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeQrPassRoute = EmployeeQrPassRouteImport.update({
  id: '/employee/qr-pass',
  path: '/employee/qr-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePaymentsRoute = EmployeePaymentsRouteImport.update({
  id: '/employee/payments',
  path: '/employee/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeNewBookingRoute = EmployeeNewBookingRouteImport.update({
  id: '/employee/new-booking',
  path: '/employee/new-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeMyBookingsRoute = EmployeeMyBookingsRouteImport.update({
  id: '/employee/my-bookings',
  path: '/employee/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeGuestHousesRoute = EmployeeGuestHousesRouteImport.update({
  id: '/employee/guest-houses',
  path: '/employee/guest-houses',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeFeedbackRoute = EmployeeFeedbackRouteImport.update({
  id: '/employee/feedback',
  path: '/employee/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeQrPassBookingIdRoute = EmployeeQrPassBookingIdRouteImport.update({
  id: '/$bookingId',
  path: '/$bookingId',
  getParentRoute: () => EmployeeQrPassRoute,
} as any)
const EmployeePaymentBookingIdRoute =
  EmployeePaymentBookingIdRouteImport.update({
    id: '/employee/payment/$bookingId',
    path: '/employee/payment/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmployeeGuestHousesIdRoute = EmployeeGuestHousesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployeeGuestHousesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/guest-houses': typeof EmployeeGuestHousesRouteWithChildren
  '/employee/my-bookings': typeof EmployeeMyBookingsRoute
  '/employee/new-booking': typeof EmployeeNewBookingRoute
  '/employee/payments': typeof EmployeePaymentsRoute
  '/employee/qr-pass': typeof EmployeeQrPassRouteWithChildren
  '/employee/guest-houses/$id': typeof EmployeeGuestHousesIdRoute
  '/employee/payment/$bookingId': typeof EmployeePaymentBookingIdRoute
  '/employee/qr-pass/$bookingId': typeof EmployeeQrPassBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/guest-houses': typeof EmployeeGuestHousesRouteWithChildren
  '/employee/my-bookings': typeof EmployeeMyBookingsRoute
  '/employee/new-booking': typeof EmployeeNewBookingRoute
  '/employee/payments': typeof EmployeePaymentsRoute
  '/employee/qr-pass': typeof EmployeeQrPassRouteWithChildren
  '/employee/guest-houses/$id': typeof EmployeeGuestHousesIdRoute
  '/employee/payment/$bookingId': typeof EmployeePaymentBookingIdRoute
  '/employee/qr-pass/$bookingId': typeof EmployeeQrPassBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/feedback': typeof EmployeeFeedbackRoute
  '/employee/guest-houses': typeof EmployeeGuestHousesRouteWithChildren
  '/employee/my-bookings': typeof EmployeeMyBookingsRoute
  '/employee/new-booking': typeof EmployeeNewBookingRoute
  '/employee/payments': typeof EmployeePaymentsRoute
  '/employee/qr-pass': typeof EmployeeQrPassRouteWithChildren
  '/employee/guest-houses/$id': typeof EmployeeGuestHousesIdRoute
  '/employee/payment/$bookingId': typeof EmployeePaymentBookingIdRoute
  '/employee/qr-pass/$bookingId': typeof EmployeeQrPassBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/help'
    | '/login'
    | '/profile'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/rooms'
    | '/employee/dashboard'
    | '/employee/feedback'
    | '/employee/guest-houses'
    | '/employee/my-bookings'
    | '/employee/new-booking'
    | '/employee/payments'
    | '/employee/qr-pass'
    | '/employee/guest-houses/$id'
    | '/employee/payment/$bookingId'
    | '/employee/qr-pass/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/help'
    | '/login'
    | '/profile'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/rooms'
    | '/employee/dashboard'
    | '/employee/feedback'
    | '/employee/guest-houses'
    | '/employee/my-bookings'
    | '/employee/new-booking'
    | '/employee/payments'
    | '/employee/qr-pass'
    | '/employee/guest-houses/$id'
    | '/employee/payment/$bookingId'
    | '/employee/qr-pass/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/help'
    | '/login'
    | '/profile'
    | '/admin/approvals'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/feedback'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/rooms'
    | '/employee/dashboard'
    | '/employee/feedback'
    | '/employee/guest-houses'
    | '/employee/my-bookings'
    | '/employee/new-booking'
    | '/employee/payments'
    | '/employee/qr-pass'
    | '/employee/guest-houses/$id'
    | '/employee/payment/$bookingId'
    | '/employee/qr-pass/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeFeedbackRoute: typeof EmployeeFeedbackRoute
  EmployeeGuestHousesRoute: typeof EmployeeGuestHousesRouteWithChildren
  EmployeeMyBookingsRoute: typeof EmployeeMyBookingsRoute
  EmployeeNewBookingRoute: typeof EmployeeNewBookingRoute
  EmployeePaymentsRoute: typeof EmployeePaymentsRoute
  EmployeeQrPassRoute: typeof EmployeeQrPassRouteWithChildren
  EmployeePaymentBookingIdRoute: typeof EmployeePaymentBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/qr-pass': {
      id: '/employee/qr-pass'
      path: '/employee/qr-pass'
      fullPath: '/employee/qr-pass'
      preLoaderRoute: typeof EmployeeQrPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/payments': {
      id: '/employee/payments'
      path: '/employee/payments'
      fullPath: '/employee/payments'
      preLoaderRoute: typeof EmployeePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/new-booking': {
      id: '/employee/new-booking'
      path: '/employee/new-booking'
      fullPath: '/employee/new-booking'
      preLoaderRoute: typeof EmployeeNewBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/my-bookings': {
      id: '/employee/my-bookings'
      path: '/employee/my-bookings'
      fullPath: '/employee/my-bookings'
      preLoaderRoute: typeof EmployeeMyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/guest-houses': {
      id: '/employee/guest-houses'
      path: '/employee/guest-houses'
      fullPath: '/employee/guest-houses'
      preLoaderRoute: typeof EmployeeGuestHousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/feedback': {
      id: '/employee/feedback'
      path: '/employee/feedback'
      fullPath: '/employee/feedback'
      preLoaderRoute: typeof EmployeeFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/qr-pass/$bookingId': {
      id: '/employee/qr-pass/$bookingId'
      path: '/$bookingId'
      fullPath: '/employee/qr-pass/$bookingId'
      preLoaderRoute: typeof EmployeeQrPassBookingIdRouteImport
      parentRoute: typeof EmployeeQrPassRoute
    }
    '/employee/payment/$bookingId': {
      id: '/employee/payment/$bookingId'
      path: '/employee/payment/$bookingId'
      fullPath: '/employee/payment/$bookingId'
      preLoaderRoute: typeof EmployeePaymentBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/guest-houses/$id': {
      id: '/employee/guest-houses/$id'
      path: '/$id'
      fullPath: '/employee/guest-houses/$id'
      preLoaderRoute: typeof EmployeeGuestHousesIdRouteImport
      parentRoute: typeof EmployeeGuestHousesRoute
    }
  }
}

interface EmployeeGuestHousesRouteChildren {
  EmployeeGuestHousesIdRoute: typeof EmployeeGuestHousesIdRoute
}

const EmployeeGuestHousesRouteChildren: EmployeeGuestHousesRouteChildren = {
  EmployeeGuestHousesIdRoute: EmployeeGuestHousesIdRoute,
}

const EmployeeGuestHousesRouteWithChildren =
  EmployeeGuestHousesRoute._addFileChildren(EmployeeGuestHousesRouteChildren)

interface EmployeeQrPassRouteChildren {
  EmployeeQrPassBookingIdRoute: typeof EmployeeQrPassBookingIdRoute
}

const EmployeeQrPassRouteChildren: EmployeeQrPassRouteChildren = {
  EmployeeQrPassBookingIdRoute: EmployeeQrPassBookingIdRoute,
}

const EmployeeQrPassRouteWithChildren = EmployeeQrPassRoute._addFileChildren(
  EmployeeQrPassRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeFeedbackRoute: EmployeeFeedbackRoute,
  EmployeeGuestHousesRoute: EmployeeGuestHousesRouteWithChildren,
  EmployeeMyBookingsRoute: EmployeeMyBookingsRoute,
  EmployeeNewBookingRoute: EmployeeNewBookingRoute,
  EmployeePaymentsRoute: EmployeePaymentsRoute,
  EmployeeQrPassRoute: EmployeeQrPassRouteWithChildren,
  EmployeePaymentBookingIdRoute: EmployeePaymentBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
